### ISSUE TITLE
Unable to download wind aloft data

### ISSUE THREAD

**Issue by andreashohl82** [JetStream96/QSimPlanner#18]
QSimPlanner is failes to download wind aloft data. This used to work but for some reason it seems to be broken.

**Comment by rklomp** [comment]
A quick look at the code and the wind source makes me think it is caused by Line 14 in LastestDataSetFinder.

https://github.com/JetStream96/QSimPlanner/blob/develop/src/QSP/WindAloft/LastestDataSetFinder.cs#L14

https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_1p00.pl gives me a list of urls, but none of the pages are >9000 chars.
So I guess the format of this page has changes and LastestDataSetFinder needs to be rewritten.

**Comment by rklomp** [comment]
I finally had the time time to setup a development environment and fix this issue
![image](https://user-images.githubusercontent.com/195939/63041683-b4595200-bec8-11e9-9be9-8a1083faa6ff.png)

I will create a pull request so the original author can merge it. I have also not updated the version number.

New installer can be found here:
https://github.com/rklomp/QSimPlanner/releases/tag/v0.4.6-windfix
