### ISSUE TITLE
Airbus Profiles

### ISSUE THREAD

**Issue by merspieler** [JetStream96/QSimPlanner#5]
Is there any way I can help with creating the profiles for the Airbus series?

**Comment by JetStream96** [comment]
A while ago, I was trying to find performance data for A320/330. The fuel burn data is easy to find as there are many other websites and application which does fuel planning. The main problem, however, is to find usable takeoff and landing data. I have not find any data source that can fit into this application as all sources I can find are incomplete.

One source is the official [airport planning manual](http://nicmosis.as.arizona.edu:8000/ECLIPSE_WEB/TSE2015/A320_DOCUMENTS/Airbus-AC-A320-Jun2012.pdf), but the takeoff distance charts (e.g. page 184) do not take wind into account. That's bad because wind is an important factor when calculating takeoff distances. Also, we do not know the flaps or surface condition (dry or wet) used for the chart.

Another source is the charts from the Airbus FCOM. Unfortunately it is incomplete as the FCOMs I can find for "A320 series" do not contain performance tables for A319 or A321.

The problem for landing distance charts/tables is similar. So I do not think there is enough data available. The simplest way is probably to record the takeoff/landing distances in the sim. Given the amount of variables (wind, air density, dry/wet, weight, temperature), it can be a very tedious task.

If you have data source or any idea about the Airbus profiles, feel free to tell me. It doesn't matter if your data format is different from the existing one. I can change the code to allow other formats. I can explain the current data format if you are interested. :)

**Comment by merspieler** [comment]
The problems with testing it in the sim would be, how realistic is the sim, the wind and plane models(I think X-Plane would give much better results than FSX cause of the way it is simulated).

Another point is, that there are different engine models which would have to be represented (and don't forget the neos ;-).

An explanation of the data format would be good somewhere in the contribution documentation.

**Comment by JetStream96** [comment]
Different engine models is indeed a problem. It's hard to say whether the performance difference between engines will be noticeable. Especially considering the sim is not a perfect match to real world either.


There are barely any explanations in the templates though. I will add some tomorrow.

**Comment by merspieler** [comment]
If all fails, i could ask a A32X pilot for more information

**Comment by merspieler** [comment]
See

http://www.cockpitseeker.com/wp-content/uploads/goodies/ac/a320/pdf/Print_Only/PTM%20with%20airbus%20doc/pdf/U0S2SP0-L.pdf 

Starting at page 28.

Hope this helps. I try to find this for the other airbus series as well.

**Comment by JetStream96** [comment]
Thanks. I have seen similar charts before. That's extracted from the FCOM, and it's probably the A320 version. I will add it if I can confirm it's indeed the A320. Still need other A320 family though.

**Comment by merspieler** [comment]
If i understood it right, you can use it for all of the A318-A321.

The only difference might be, that an A321 can't have a low weight as an A318 so the lower part of the table would be cut off( same could apply [I'm not sure about this] for the A318 with a max landing weight below the top charted weight).

**Comment by merspieler** [comment]
Found similar documents for the A330 and A340

A330:
+ http://www.avialogs.com/index.php/en/aircraft/europe-and-consortiums/airbus/a330/airbus-330-fcom-flight-preparation-vol-2.html
+ TO : p124
+ LDG: p146

A340:
+ http://www.avialogs.com/index.php/en/aircraft/europe-and-consortiums/airbus/a340/airbus-340-fcom-flight-preparation-vol-2.html
+ TO: p124
+ LDG: p169

**Comment by JetStream96** [comment]
> If i understood it right, you can use it for all of the A318-A321.
> The only difference might be, that an A321 can't have a low weight as an A318 so the lower part of the table would be cut off( same could apply [I'm not sure about this] for the A318 with a max landing weight below the top charted weight).

I don't think that is true. I tried to use the same weight and conditions to compute the takeoff distances for 737-600 to 900, and the results are not the same. I got 1100, 1044, 1101, 1187 meters. The difference between the smallest and largest is 13%.

**Comment by merspieler** [comment]
Your right... I've done more research... there are even differences between the A320...

You'll have to add it for each version (I listed here only the A320 versions)...
A320-111 (CFM56-5A1)
A320-214 (CFM56-5B4)
A320-232 (IAE V2527-A5)

neo
A320-251N (LEAP-1A26)
A320-271N (PurePower 1127G)

**Comment by JetStream96** [comment]
Yeah I think you are right. I kind of ignore the performance differences between different engines for aircrafts currently in the application, such as 737s and 777s. I doubt this small difference is accurately reflected in the sim anyway, at least for most addons. 

I want to go for a more practical approach. Despite the lack of comprehensive data, I think there is still a way to 'approximate' the real performance (for takeoff and landing, since data for fuel calculation is plenty). I am trying to think of way to approximate this. Do you have any ideas about this?
